### ISSUE TITLE
React3Renderer error

### ISSUE THREAD

**Issue by leonardreidy** [cannc4/Siren#23]
Cool project! Just cloned and installed the repo, fails to compile because of a problem with React3Renderer. Google search is giving me nothing. Any ideas? Here's the error: 

`Error in ./~/react-three-renderer/lib/React3Renderer.js
Module not found: Error: Cannot resolve module 'react/lib/ReactComponent' in /home/dev/Documents/SIREN/Siren/node_modules/react-three-renderer/lib
 @ ./~/react-three-renderer/lib/React3Renderer.js 21:23-58`

**Comment by cannc4** [comment]
thanks @leonardreidy 
Try deleting everything related with `react-three` from `package.json` and other imports. 

If it doesn't do it, we are about to do a major update and it should be fixed then

**Comment by leonardreidy** [comment]
Thanks for your help! Removing react-three freed up the front-end but there are some other errors now. That's ok. I'll wait until the next update. Keep up the good work. It looks like a really cool application.
