### ISSUE TITLE
nom start isn't going through

### ISSUE THREAD

**Issue by freekatet** [cannc4/Siren#29]
hey
on el captain

here is whats happening for me

any idea how to fix this?

thanks

Failed to compile.

Error in ./src/actions/index.js
Module build failed: Duplicate declaration "exitSC"

  416 | 	}
  417 | }
> 418 | export const exitSC = (server) => {
      |              ^
  419 |   return dispatch => {
  420 |     axios.get('http://' + server.replace('http:', '').replace('/', '').replace('https:', '') + '/tidal')
  421 |     .then((response) => {

 @ ./src/components/Patterns.react.js 19:15-36

**Comment by andresgottlieb** [comment]
Same thing happens to me on Sierra 10.12.6

**Comment by cannc4** [comment]
Hello, you won't be experiencing this issue in `0.5-dev` which is latest branch and will be merged into master soon
